### ISSUE TITLE
Tests fail with link error

### ISSUE THREAD

**Issue by djc** [jeremydavis519/runtime-macros#1]
I'm trying runtime-macros for the first time (and am aiming to add support for custom derives). However, I cannot get the tests to pass without any changes on my Linux machine:

error: linking with `x86_64-pc-linux-gnu-gcc` failed: exit code: 1
  |
  = note: "x86_64-pc-linux-gnu-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert0.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert1.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert10.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert11.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert12.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert13.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert14.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert15.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert2.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert3.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert4.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert5.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert6.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert7.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert8.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.custom_assert9.rcgu.o" "-o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/libcustom_assert-d0d1faa87058288a.so" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.crate.metadata.rcgu.o" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/custom_assert-d0d1faa87058288a.crate.allocator.rcgu.o" "-Wl,-z,relro,-z,now" "-nodefaultlibs" "-L" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/libsyn-b17cb5a42dffe8fb.rlib" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/libquote-190a00b8cfc52657.rlib" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/libproc_macro2-5afa4ee5f6cd19d0.rlib" "/home/djc/src/runtime-macros/examples/custom_assert/target/debug/deps/libunicode_xid-5bc421b83fcc3ab5.rlib" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-l" "proc_macro-119e6844818df36c" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax-6b1de165a07b1466" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_errors-97704bdb7935a7a2" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax_pos-0fa6923d83d8c437" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_data_structures-f28ae370516752bd" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "serialize-6bce5699e5acb3d9" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_cratesio_shim-469e8868784d6048" "-Wl,--start-group" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-1abdb6e6c6cf07b3" "-Wl,--end-group" "-Wl,-Bstatic" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-60c2f7e3c12510c8.rlib" "-Wl,-Bdynamic" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util" "-shared" "-no-pie"
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/crt1.o: In function `_start':
          (.text+0x20): undefined reference to `main'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

test tests::proc_macro_coverage ... FAILED

failures:

---- tests::proc_macro_coverage stdout ----
	Building project
thread 'tests::proc_macro_coverage' panicked at 'called `Result::unwrap()` on an `Err` value: -1', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    tests::proc_macro_coverage

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'

**Comment by jeremydavis519** [comment]
I'm pretty sure I never saw the notification for this issue. Sorry about that. I've figured out what went wrong and will have the fix committed by tomorrow.

The main issue was that you needed to set the `RUSTFLAGS` environment variable to `"--cfg procmacro2_semver_exempt"`, which apparently wasn't necessary when I first published this crate. That's only necessary when you're testing this crate, though, and it's because this crate lists [`cargo-tarpaulin`](https://crates.io/crates/cargo-tarpaulin) under `dev-dependencies`.

I'm updating the Travis test to set that flag and to do periodic tests in case something like this happens again. And while I'm at it, I'm taking the opportunity to update the crate's dependencies.

It seems like the crate itself still worked, even if the test didn't.
